# Generated by Django 2.2.5 on 2019-10-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarFlare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classType', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NasaEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('solarEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nasa.SolarFlare')),
            ],
        ),
    ]
