# Generated by Django 2.2.5 on 2019-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0002_auto_20191019_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarflare',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
