# Generated by Django 2.2.5 on 2019-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0003_auto_20191019_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarbody',
            name='gravity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solarbody',
            name='englishName',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
