# Generated by Django 2.2.5 on 2019-10-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('nasa_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nasa.NasaEvent')),
            ],
        ),
    ]
