# Generated by Django 2.2.5 on 2019-10-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_mass', models.CharField(blank=True, max_length=255, null=True)),
                ('atomic_number', models.CharField(blank=True, max_length=255, null=True)),
                ('atomic_radius', models.IntegerField(blank=True, max_length=255, null=True)),
                ('boiling_point', models.IntegerField(blank=True, null=True)),
                ('bonding_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cpk_hex_color', models.CharField(blank=True, max_length=255, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('electron_affinity', models.IntegerField(blank=True, null=True)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('electronic_configuration', models.CharField(blank=True, max_length=255, null=True)),
                ('group_block', models.CharField(blank=True, max_length=255, null=True)),
                ('ion_radius', models.CharField(blank=True, max_length=255, null=True)),
                ('ionization_energy', models.CharField(blank=True, max_length=255, null=True)),
                ('melting_point', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('oxidation_states', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_state', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('van_der_waal_radius', models.IntegerField(blank=True, null=True)),
                ('year_discovered', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
